name: Continuous Integration

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/practic:0.0.2 docker
      
    - name: Push Docker image to Docker Hub
      run: sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/practic:0.0.2
